### PR TITLE
Add technical approach document

### PR DESCRIPTION
**Pull request by mheadd**
Add a first draft of a technical approach document, to help prospective vendors better understand the project and the current IT landscape.

### CODE REVIEW

**Comment by mheadd** [comment]
@sztaylorakgov Can you take a look at this pull request and suggest any potential changes (if any)? Thanks!

**Comment by sztaylorakgov** [comment]
This looks good to me, @mheadd!

**Comment by sztaylorakgov** [comment]
Oops!  Clicked the wrong button -- fixed it!

**Review by sztaylorakgov — APPROVED** [review]
This all looks right to me, @DanaPenner.

**Pull request merged**
